operation/bedapp/urls.py
from django.urls import path, include
from .views import BedView

app_name = 'bedapp'

urlpatterns = [
    path('', BedView, name='bed'),
    path('update/<int:pk>', BedView, name='bed_update'),
]

operation/operation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'bed/', include('bedapp.urls') ),
    path( 'patient/', include('patientapp.urls') ),
    path( 'visit/', include( 'visitapp.urls' ) ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media setting

operation/patientapp/urls.py
from django.urls import path, include
from patientapp.views import PatientCreateView,PatientUpdateView, PatientDetailView

app_name = 'patientapp'

urlpatterns = [
    path( 'create/', PatientCreateView.as_view(), name='patient_create'),
    path( 'update/<int:pk>',PatientUpdateView.as_view(), name='update' ),
    path( 'detail/<int:pk>', PatientDetailView.as_view(), name='detail'),

]

operation/visitapp/urls.py
from django.urls import path, include


app_name = 'visitapp'

urlpatterns = [


]

operation/bedapp/models.py
from django.db import models
from patientapp.models import Patient
# Create your models here.

class Acting(models.Model):
    act = models.CharField(max_length=10)
    time = models.IntegerField()

    def __str__(self):
        return self.act

class ActingSet(models.Model):
    name = models.CharField(max_length=10)
    set = models.ManyToManyField(Acting)

    def __str__(self):
        return self.name

class Bed(models.Model):
    bed_num = models.CharField(max_length=5)
    bed_act = models.ForeignKey(ActingSet,blank=True,null=True, on_delete=models.SET_NULL)
    patient = models.ForeignKey(Patient,blank=True,null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.bed_num

operation/patientapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Patient(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, db_index=True,allow_unicode=True)
    phone_num = models.PositiveIntegerField()
    birthday = models.PositiveIntegerField()
    reg_num = models.PositiveIntegerField()
    address = models.TextField(blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at','-created_at']
        index_together = [['id','slug']]

    def get_absolute_url(self):
        return reverse('patientapp:product_detail', args=[self.id,self.slug])

    def __str__(self):
        return self.name

operation/visitapp/models.py
from django.db import models
from django.urls import reverse
from patientapp.models import Patient
# Create your models here.

class Symptoms(models.Model):
    name = models.CharField(max_length=10)

class Visit(models.Model):
    patient = models.ForeignKey(Patient,on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, db_index=True,allow_unicode=True)
    symptom = models.ManyToManyField(Symptoms)
    created_at = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-created_at']
        index_together = [['id','slug']]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id,self.slug])

    def __str__(self):
        return self.name

operation/bedapp/forms.py
from django.forms import ModelForm

from bedapp.models import Bed


class BedForm(ModelForm):
    class Meta:
        model = Bed
        fields = ['bed_act','patient']

operation/patientapp/forms.py
from django.forms import ModelForm

from patientapp.models import Patient


class PatientCreationForm(ModelForm):
    class Meta:
        model = Patient
        fields = ['name','phone_num','birthday','reg_num','address','description']

operation/bedapp/views.py
from django.shortcuts import render
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView
# Create your views here.
from .models import *
from .forms import BedForm


def BedView(request):
    beds = Bed.objects.all()

    return render(request,
                  'bedapp/bed.html',
                  {
                    'beds':beds,
                   }
                  )

class BedUpdateView(UpdateView):
    model = Bed
    form_class = BedForm
    context_object_name = 'target_bed'
    template_name = 'bedapp/update.html'

    def get_success_url(self):
        return reverse('patientapp:detail', kwargs={'pk': self.object.pk})

class PatientDetailView(DetailView):
    model = Bed
    context_object_name = 'target_bed'
    template_name = 'bedapp/detail.html'

operation/patientapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView

from patientapp.models import Patient
from patientapp.forms import PatientCreationForm


class PatientCreateView(CreateView):
    model = Patient
    context_object_name = 'target_patient'
    form_class = PatientCreationForm
    template_name = 'patientapp/create.html'


    def get_success_url(self):
        return reverse('patientapp:detail', kwargs={'pk': self.object.pk})

    # def form_valid(self, form):
    #     temp_patient = form.save(commit=False)
    #     temp_patient.patient = self.request.patient
    #     temp_patient.save()
    #
    #     return super().form_valid(form)

class PatientUpdateView(UpdateView):
    model = Patient
    form_class = PatientCreationForm
    context_object_name = 'target_patient'
    template_name = 'patientapp/update.html'

    def get_success_url(self):
        return reverse('patientapp:detail', kwargs={'pk': self.object.pk})

class PatientDetailView(DetailView):
    model = Patient
    context_object_name = 'target_patient'
    template_name = 'patientapp/detail.html'

operation/visitapp/views.py
from django.shortcuts import render

# Create your views here.

operation/bedapp/templates/bedapp/bed.html
{% extends 'base.html' %}
{% block content %}



<div style='text-align: center; max-width: 500px; margin: 4rem auto'>

  <div class="container">
  <div class="row">
    {% for bed in beds%}
    <div class="col">
      {{ bed.bed_num }}
    </div>
    {% endfor %}
    <div class="col">
      Column
    </div>
    <div class="col">
      Column
    </div>
  </div>
</div>




</div>


{% endblock %}

operation/patientapp/templates/patientapp/create.html
{% extends 'base.html' %}
{% block content %}



<div style='text-align: center; max-width: 500px; margin: 4rem auto'>
  <div><h4>환자 정보 입력</h4></div>
  <!-- enctype -> img넣을때 꼭필요 -->
  <form action="{% url 'patientapp:patient_create' %}" method="POST" enctype="multipart/form-data">

<!--    {{form.name}}-->
<!--    {{form.phone_num}}-->
<!--    {{form.birthday}}-->
<!--    {{form.reg_num}}-->
<!--    {{form.address}}-->
<!--    {{form.description}}-->
    {{form.as_p}}

    {% csrf_token %}

    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
  </form>

</div>


{% endblock %}

operation/patientapp/templates/patientapp/detail.html
{% extends 'base.html' %}
{% block content %}

<div style='text-align: center; max-width: 500px; margin: 4rem auto'>
  <div>
    <p>
      {{ target_patient.created_at }}
    </p>
    <h2 style="font-family:'NanumSquareB';">
      {{ target_patient.name }}
    </h2>
    <a href="{% url 'patientapp:update' pk=target_patient.pk %}">
          변경
    </a>


  </div>
</div>


{% endblock %}

operation/patientapp/templates/patientapp/update.html
{% extends 'base.html' %}

{% block content %}



<div style='text-align: center; max-width: 500px; margin: 4rem auto'>
  <div><h4>환자 정보 변경</h4></div>

  <form action="{% url 'patientapp:update' pk=target_patient.pk %}" method="POST"  enctype="multipart/form-data">
    {{form.as_p}}

    {% csrf_token %}

    <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
  </form>

</div>


{% endblock %}

operation/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'NanumSquareR';">
{% include 'header.html' %}
{% include 'sidebar.html' %}

{% block content %}
{% endblock %}


{% include 'footer.html' %}


</body>
</html>

operation/templates/footer.html
<div class="tatoa_footer">
  <div class="tatoa_footer_button">
    <span>공지사항</span> |
    <span>제휴문의</span> |
    <span>서비스소개</span> |
    <span>오시는길</span>
  </div>
  <div><h6 class="tatoa_footer_logo">tatoa</h6></div>
</div>

operation/templates/head.html
{% load static %}


<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- boot strap links -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- google font link -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,600&display=swap" rel="stylesheet">
  <title>Document</title>

  <style>
    @font-face {
      font-family: NanumSquareR;
      src: local('NanumSquareR'),
      url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
    }
    @font-face {
      font-family: NanumSquareB;
      src: local('NanumSquareB'),
      url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
    }
    
  </style>
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

</head>

operation/templates/header.html
<div>
<div class="tatoa_header">
  <h1 class="tatoa_header_logo">tatoa</h1>
</div>
<div class="tatoa_header_nav">


  <!-- request.path는 원래자리대로 돌아가는거 -->

  <a href="{% url 'patientapp:patient_create' %}">
    <span>환자등록</span>
  </a>


</div>

</div>

operation/templates/sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>